apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi_app
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000  # Choose a port in the range 30000-32767 (or use "0" for a randomly allocated port)
